name: Visual Studio x64 release Build Check

on:
    push:
        branches: [stable]
    pull_request:
        branches: [stable]

permissions:
    contents: read

jobs:
    build:
        name: Visual Studio x64 release Build Check
        runs-on: windows-latest

        steps:
            - name: Check out code from GitHub
              uses: actions/checkout@v7

            - name: Setup MSVC compiler
              uses: ilammy/msvc-dev-cmd@v1

            - name: Building project
              run: |
                  msbuild src/bios.sln -t:Rebuild -p:Configuration=Release -p:Platform=x64
                  tree /f

            - name: Set outputs
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Archive artifact
              uses: actions/upload-artifact@v4
              with:
                  name: bios_${{ steps.vars.outputs.sha_short }}
                  path: |
                      src/built/DragonBurn-usermode.exe
